interface Entry {
  n: number;
  label: string;
  body: string;
}

const ENTRIES: Entry[] = [
  {
    n: 1,
    label: "Promise to Audience (Learning Outcome)",
    body: "By the time you leave this page, you should be able to look at a claim like \"kids from wealthier families score higher on IQ tests\" and ask better questions about it — what's being measured, what's driving the difference, and what would actually change it. That's the goal. Not a number about you.",
  },
  {
    n: 2,
    label: "Definition (What)",
    body: "This is an interactive page built on one synthetic dataset: 50,000 simulated children, each with an IQ score attached to roughly 30 background factors — parental IQ, income, prenatal care, home environment, and more. You can build a rough version of your own background and see where it lands, then explore how the underlying factors relate to each other.",
  },
  {
    n: 3,
    label: "When Scenario",
    body: "The dataset models children roughly ages 6 to 12, born between 2005 and 2020 — the window where most of these environmental and prenatal factors are still being measured and where cognitive testing is common. It's a snapshot of childhood, not adulthood, and not a lifetime.",
  },
  {
    n: 4,
    label: "Why Purpose",
    body: "IQ gets thrown around casually — as an insult, a compliment, an excuse. This page exists to slow that down a little: to show, with real numbers, how much of what gets credited to \"natural ability\" is shaped by things like nutrition, stress, and stimulation, and how much genuinely isn't something anyone chose.",
  },
  {
    n: 5,
    label: "Who | Anthropology",
    body: "The simulated population is meant to resemble a general population of children born in the 2000s and 2010s — not any one country specifically, and not skewed toward any particular group. It doesn't include race or ethnicity as a factor at all, on purpose: treating group IQ differences as genetic isn't supported by the science, so that variable was left out of the simulation entirely.",
  },
  {
    n: 6,
    label: "How Method",
    body: "The dataset wasn't collected from real children. It was generated by a program that starts from realistic relationships between variables — pulled from published research — and produces thousands of plausible children consistent with those relationships. This page then processes that data once, ahead of time, into small summary files, so nothing has to be recalculated in your browser.",
  },
  {
    n: 7,
    label: "Tools",
    body: "The dashboard is built with React and TypeScript, and every chart is hand-drawn in SVG rather than pulled from a charting library — partly for control over the visual language, and partly because the usual chart types (bar charts, pie charts) didn't fit what these questions needed.",
  },
  {
    n: 8,
    label: "What We Want to Test & Observe Changes",
    body: "The central question: does a child's environment predict IQ better than the parents' IQ does? And more specifically — when you combine several environmental factors instead of looking at them one at a time, how much do they explain together, once you account for the fact that many of them overlap?",
  },
  {
    n: 9,
    label: "Hypothesis: Optimistic Prediction",
    body: "Before building this, a reasonable guess might have been that genetics would dominate the picture and environment would be a secondary, modest factor. The more hopeful possibility — and the dataset's own headline claim — is the opposite: that environment predicts more than parental IQ does, and that most of what environment contributes is something people can actually change.",
  },
  {
    n: 10,
    label: "Conditioning Variables",
    body: "Some things in this dataset aren't choices at all — birth year, birth order, the mother's age at birth. These aren't treated as good or bad; they're just part of the circumstances a child is born into, included so the model has a realistic starting point rather than a blank slate.",
  },
  {
    n: 11,
    label: "Manipulatable Variables",
    body: "Screen time, books in the home, how much reading and talking a child is exposed to, early education, nutrition — these are the factors a caregiver, teacher, or policy could still influence today. Individually smaller than genetics or family income, but the only ones on this list anyone can actually act on.",
  },
  {
    n: 12,
    label: "Context of Study",
    body: "This sits between two fields that don't always talk to each other: developmental research, which studies what actually shapes a child's cognitive growth, and data visualization, which studies how to show people numbers they can actually use. Neither one alone was going to be enough here.",
  },
  {
    n: 13,
    label: "Floor",
    body: "The lowest-effort version of this page would have been a single static chart with a caption underneath it — technically accurate, but not something anyone would want to look at twice.",
  },
  {
    n: 14,
    label: "Ceiling",
    body: "The highest possible score on this page's own index — every environmental factor set to its best value — lands around the top 2% of the simulated population. That's a hard limit, not a bug: the two strongest predictors in the whole dataset, the parents' own IQ scores, were deliberately left out of what this tool asks you, so no combination of the remaining factors can score higher. The case study further down shows this number computed live, not written in as a fixed claim.",
  },
  {
    n: 15,
    label: "Irreducible Blocks — Catalyst, Operation, Function",
    body: "Think of a child's outcome as a small machine. Genetics and the family's starting circumstances are the catalyst — what sets things in motion before birth. Pregnancy, birth, and the home environment are the operation — the ongoing process that shapes a child day to day. The measured IQ score at the end is the function: one narrow readout of everything that came before it, not the whole story.",
  },
  {
    n: 16,
    label: "Design Process",
    body: "This started as a plain dashboard — charts, numbers, filters. It became something closer to a public exhibit once it was clear that a chart alone doesn't teach anyone anything; the reasoning behind the chart does. Each version added a layer: first the charts, then a way to place yourself among them, then plain explanations of what each chart shows, then the thinking behind the whole approach.",
  },
  {
    n: 17,
    label: "Strength",
    body: "The dataset is unusually upfront about its own assumptions — it names exactly which published research its numbers are calibrated against, instead of asking you to just trust it. That made it possible to build every number on this page so it traces back to something specific: a group average, a correlation, a named source.",
  },
  {
    n: 18,
    label: "Weaknesses",
    body: "It's still a simulation, not real data, and it's limited to the roughly 30 things it measures. No twin studies, no long-term follow-up, no measurement error, no neighborhood or school quality beyond \"had preschool or not.\" And IQ itself is a narrow slice of what makes a child's mind interesting — this page says that outright rather than letting the charts imply otherwise.",
  },
  {
    n: 19,
    label: "Opportunity",
    body: "The same approach — build a profile, place it on a real distribution, show your position as a range instead of a falsely precise number — could work for almost any outcome, not just IQ. Nothing about the underlying mechanics is specific to cognition.",
  },
  {
    n: 20,
    label: "Threats / Challenges",
    body: "The obvious risk with a page like this is that someone reads the big number as a verdict about themselves or their child, instead of what it actually is: a rough placement based on a handful of factors, with most of the picture missing. That risk gets addressed directly and more than once here, rather than buried in fine print.",
  },
  {
    n: 21,
    label: "Benefits of Research",
    body: "Knowing which factors actually move the outcome — and which ones are just correlated with something else that does — matters well beyond this page. It's the same distinction between a public-health dollar well spent and one that isn't.",
  },
  {
    n: 22,
    label: "Application to Self",
    body: "If nothing else, this is a chance to see your own background as one point among fifty thousand, rather than a fixed story about yourself — and to notice which parts of that story were never really a choice, and which parts still could be, for someone else.",
  },
  {
    n: 23,
    label: "Application to Social",
    body: "At a larger scale, this is the same logic behind real public-health decisions — iodine supplementation, lead abatement, early-childhood education funding. Knowing environment predicts more than genetics, and that some environmental effects are large and well documented, is part of the case for funding them.",
  },
  {
    n: 24,
    label: "Interests",
    body: "The most interesting part of building this wasn't the charts — it was watching an assumption break. Combining several \"environmental\" factors the naive way made them look more powerful together than they actually were, because they overlap. Fixing that changed the numbers, not just the code.",
  },
  {
    n: 25,
    label: "Early Challenges",
    body: "The profile index originally added up each factor's own correlation with child IQ, one at a time. It looked reasonable and it was wrong — it counted overlapping information more than once. That bug, and the fix for it, is written up in full further down, with the actual numbers from before and after.",
  },
  {
    n: 26,
    label: "Sensitivity",
    body: "One question on this page asks about adverse childhood experiences — a real and sometimes painful topic. It's marked optional, explained as private, and never sent anywhere; nothing typed into this page leaves your browser.",
  },
  {
    n: 27,
    label: "Overlooked Factors Discovered",
    body: "A few things weren't obvious until the charts were built rather than just described. Children of very high-IQ parents land well above average themselves, but noticeably below their parents — a well-documented pattern called regression to the mean, and it's much clearer as a chart than as a sentence. The correlation matrix also turned up more overlap between \"separate\" environmental factors than expected going in.",
  },
  {
    n: 28,
    label: "Data Collection",
    body: "Nothing was collected from real people. Every row was generated by a program, seeded to be reproducible, and calibrated against published research rather than invented from scratch.",
  },
  {
    n: 29,
    label: "Data Representation",
    body: "No pie charts, no plain bar charts. Each chart form was picked for the specific question it had to answer — a dot plot for comparing groups against an average, a dumbbell chart for the size of a gap, a density curve for a distribution's shape, a matrix for how variables overlap with each other.",
  },
  {
    n: 30,
    label: "Key Summary",
    body: "Environment predicts a child's IQ better than parental IQ does, in this simulation. Most of what environment contributes is something a caregiver could still influence. The strongest single predictors — the parents' own IQ — were deliberately left out of what this tool asks you, so treat every number on this page as a partial picture, not a verdict.",
  },
  {
    n: 31,
    label: "Innovation Solution",
    body: "The main technical contribution here isn't the charts — it's the profile engine underneath them, which corrects for overlap between factors instead of naively adding their effects together, and which computes its own honest ceiling live, rather than asserting one.",
  },
  {
    n: 32,
    label: "Reference",
    body: "See Further reading, above, for the specific studies behind the reasoning on this page.",
  },
];

export function ProjectStructure() {
  return (
    <div className="project-structure">
      {ENTRIES.map((e) => (
        <div className="project-structure-item" key={e.n}>
          <h4>
            <span className="project-structure-num">{e.n}</span>
            {e.label}
          </h4>
          <p>{e.body}</p>
        </div>
      ))}
    </div>
  );
}
